app: 
  image: busybox
  volumes: 
    - src/.:/var/www/phpapp

nginx: 
  build: docker/images/nginx 
  ports: 
    - "8080:80" 
  links: 
    - php
  volumes_from: 
    - app 

php: 
  image: php:5.6-fpm
  volumes_from: 
    - app 